version: '3'
services:

  database:
    image: 'bitnami/mariadb:latest'
    environment:
      MARIADB_USER: drupal
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: drupal
      MARIADB_ROOT_PASSWORD: password
    expose:
      - "3306"
    ports:
      - "3306:3306"
    network_mode: bridge
    container_name: drupal_db
    restart: always