<?php

/**
 * @file
 * Contains drupal_cj_test.module.
 * @defgroup entity_test Example: Content Entity
 * @ingroup examples
 * @{
 * Implment a Content Entity.
 *
 * This modules demonstrates implementing a Content Entity.
 * Fieldable Content Entity.
 * }
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drupal_cj_test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the entity_test module.
    case 'help.page.entity_test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
