<?php

/**
 * @file
 * Contains upc_salesforce.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function upc_salesforce_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the upc_salesforce module.
    case 'help.page.upc_salesforce':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('UPC Salesforce Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function upc_salesforce_theme() {
  return [
    'upc_salesforce' => [
      'render element' => 'children',
    ],
  ];
}
