upc_marketplace.mp_cont_ent_type.*:
  type: config_entity
  label: 'Marketplace Content Entity type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
