upc_marketplace.mp_elem_ent_type.*:
  type: config_entity
  label: 'Marketplace Element Entity type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
